### ISSUE TITLE
Consider renaming hack classes namespace from "_" to "h-"

### ISSUE THREAD

**Issue by renatodeleao** [whitesmith/qnorr-styles#38]
### Reasons:
1. Consistency with other namespaces
1. `_` looks like lodash 
1. `_` looks an element that is missing its block (BEM)
1. `_` looks like fake private vars in javascript
  

### Cons:
1. `h-` is not immediately recognisable, but we may argue that non of the other is

### Alternatives:
-  `hk-` but i looks like hong kong
- `hack-` is not that long and is explicit (so bonus points for clarity, but loose on consitency)

**Comment by tomasmcm** [comment]
@renatodeleao why can't they be utilities?

**Comment by renatodeleao** [comment]
Well they can but, but usually they don't fall in the same category.

- Hacks are usually a signal of [bad css or temporary workaround](https://csswizardry.com/2015/03/more-transparent-ui-code-with-namespaces/#hack-namespaces-_), not permanent as utilties
- First they aren't single declaration by nature. 99% of utilities are (or should be). 
- The fact that they look different/ugly `_my-hack-class` triggers the spider of other developers "🤔 something's not right here"
- At the moment the only hack that we have is that workaround for [min-height flex bug in Internet Explorer](https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items), and it could be an utility but then people would question its usage "the why it's there"

  ```html
  <!-- this is applying a min-heigh to c-somecompnent, no questions asked -->
  <div class="c-somecomponent u-flex-min-height">
    <div class="c-hero">
   
  <!-- this is applying min-height to c-somecomponent, 🤔 but why the ugly duck name? -->
  <div class="c-somecomponent _flex-min-height">
    <div class="c-hero">
  ```

- The guru Roberts, also says to one off hacks related to component, but i don't buy it:

```scss
// Roberts example
@media screen and (max-width: 30em) {

  /**
   * We need to force the footer to be a fixed height on smaller screens.
   */
  ._c-footer-mobile {
    height: 80px;
  }

}
```

```scss
// me
@media screen and (max-width: 30em) {

  /**
   * Well if We need to force the footer, that's part of the component so
   */
  .c-footer {
    height: 80px;
  }
}
```
This is more like a meta question, but thanks for your interest!
